src/parts/Dodo/Dodo.Web/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Dodo.Web.Controllers
{
    public class AdminController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [Route("/admin/configure")]
        public IActionResult Configure()
        {
            return View();
        }

        [Route("/admin/configure/iconwall")]
        public IActionResult ConfigureIconWall()
        {
            return View();
        }

        [Route("/admin/workflow")]
        public IActionResult Workflow()
        {
            return View();
        }

    }
}

src/parts/Dodo/Dodo.Web/Controllers/FileWorkController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Dodo.Web.Controllers
{
    public class FileTaskModel
    {
        public ApplicationHelpers.Task Task {get;set;}
        public System.Dynamic.ExpandoObject File { get; set; }
    }

    public class FileWorkController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [Route("/files/{fileId}/tasks/{taskId}")]
        public IActionResult Task(Guid fileId, Guid taskId)
        {
            var task = ApplicationHelpers.TaskHelper.GetTaskById(taskId);
            var file = ApplicationHelpers.FileHelper.GetFileById(fileId);
            ViewData["fileId"] = fileId;
            ViewData["taskId"] = taskId;
            return View(new FileTaskModel { File = file, Task = task } );
        }
    }
}

src/parts/Dodo/Dodo.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Dodo.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

src/parts/Dodo/Dodo.Web/Controllers/NewFileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Dodo.Web.Controllers
{
    public class NewFileController : Controller
    {
        [Route("/iconwall")]
        public IActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// both new file and resume will be here.
        /// </summary>
        /// <param name="formName"></param>
        /// <param name="fileId"></param>
        /// <returns></returns>
        [Route("/files/new/{formName}")]
        public IActionResult NewFile(string formName)
        {
            ViewData["formName"] = formName;
            // var fileId = Request.QueryString["file"];
            return View();
        }
    }
}

src/parts/Dodo/Dodo.Web/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Dodo.Web.Controllers
{
    public class SearchController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [Route("search/patients")]
        public IActionResult SearchPatient()
        {
            return View();
        }

        
    }
}

src/parts/Dodo/Dodo.Web/Controllers/TasksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Dodo.Web.Controllers
{
    public class TasksController : Controller
    {
        public IActionResult Index()
        {
            string uid = "someone";
            ViewData["uid"] = uid;
            return View(ApplicationHelpers.TaskHelper.GetTasksForUser(uid)); 
        }

        [Route("/users/{uid}/tasks")]
        public IActionResult TaskByUser(string uid)
        {
            ViewData["uid"] = uid;
            return View(ApplicationHelpers.TaskHelper.GetTasksForUser(uid));
        }
    }
}

src/parts/Dodo/Dodo.Web/Views/FileWork/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>File Work</h2>

src/parts/Dodo/Dodo.Web/Views/FileWork/Task.cshtml
@{
    ViewData["Title"] = "Task";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@section Scripts
 {
    <script type="text/javascript">
        function submitActivity() {
            let activity = JSON.parse($("#taActivity").val());
            let completeTask = $("#cbCompleteTask").prop("checked");
            const fileid = $("#fileId").val();
            const taskid = $("#taskId").val();
            const url = "/api/files/" + fileid + "/tasks/" + taskid;
            let data = {
                activity: activity,
                formName: '@Model.Task.FormName',
                completeTask: completeTask
            };
            
            $.ajax({
                url: url,
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                type: "POST",
                data: JSON.stringify(data),
                success: function (result) {
                    debugger;
                }

            });
        };
    </script>
}

<h2>Task</h2>

Adding @Model.Task.Type to file @ViewData["fileId"] for task @ViewData["taskId"] using Form @Model.Task.FormName
<input type="hidden" id="fileId" value="@ViewData["fileId"]" />
<input type="hidden" id="taskId" value="@ViewData["taskId"]" />
<hr/>
<dl>
    <dt>Type</dt><dd>@Model.File.IncidentType</dd>
    <dt>Severity</dt><dd>@Model.File.Severity</dd>
    <dt>State</dt><dd>@Model.File.State</dd>
    <dt>Details</dt><dd>@Model.File.Details</dd>
</dl>
<hr/>
<h3>Form @Model.Task.FormName</h3>
<div>
    <textarea id="taActivity">
        {"communication": "Call", "doneBy": "Jian"}
    </textarea>
    <input type="checkbox" id="cbCompleteTask" />Complete the task
    <button id="btnOK" onclick="submitActivity()">Submit</button>
</div>
  

src/parts/Dodo/Dodo.Web/Views/NewFile/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Iconwall</h2>

src/parts/Dodo/Dodo.Web/Views/NewFile/NewFile.cshtml
@{
    ViewData["Title"] = "NewFile";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Scripts
{
    <script type="text/javascript">
        function submitFile() {
            var file = JSON.parse($("#taFile").val());
            var data = { file: file };
            $.ajax({
                url: "/api/files/new",
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                type: "POST",
                data: JSON.stringify(data),
                success: function (result) {
                    debugger;
                }

            });
        };
    </script>
}
<h2>Submission Form using @ViewData["formName"]</h2>

<textarea id="taFile">
{ "fileId": 1, "tenantId": "fef554a9-e234-4177-8dac-0680702d4ec7", "unitId": "e1b05144-be56-4d9e-a8fb-c966fb7d8bc2", "type": "Fall", "severity": "Injury", "submittedBy": "a@b.com", "details": {
        "patient": "jian zhou",
        "age": 45,
        "gender": "male"
    }
}
</textarea>

<button id="btnSubmit" type="button" onclick="submitFile()">Submit</button>

src/parts/Dodo/Dodo.Web/Views/Search/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Search</h2>

src/parts/Dodo/Dodo.Web/Views/Search/SearchPatient.cshtml
@{
    ViewData["Title"] = "SearchPatient";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Search Patient</h2>
Patient Centric View?

src/parts/Dodo/Dodo.Web/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Dodo.Web</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Dodo.Web</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="NewFile" asp-action="Index">New</a></li>
                    <li><a asp-area="" asp-controller="Search" asp-action="Index">Search</a></li>
                    <li><a asp-area="" asp-controller="Tasks" asp-action="Index">Tasks</a></li>
                    <li><a asp-area="" asp-controller="Admin" asp-action="Index">Admin</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - Dodo.Web</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

src/parts/Dodo/Dodo.Web/Views/Tasks/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>User @ViewData["uid"]'s Tasks</h2>

<ul>
    @foreach (var item in Model)
    {
        <li><a href="/files/@item.FileId/tasks/@item.Id">@item.Subject</a></li>
    }
</ul>

src/parts/Dodo/Dodo.Web/Views/Tasks/TaskByUser.cshtml
@model IEnumerable<Dodo.Web.ApplicationHelpers.Task>

    @{
        ViewData["Title"] = "TaskByUser";
        Layout = "~/Views/Shared/_Layout.cshtml";
    }

    <h2>User @ViewData["uid"]'s Tasks</h2>

    <ul>
        @foreach (var item in Model)
        {
            <li><a href="/files/{@item.FileId}/tasks/{@item.Id}">@item.Subject</a></li>
        }
    </ul>